FROM mongo:4.2.0
MAINTAINER Minoru Gondo
RUN mkdir -p /var/www/projeto_programador_database
COPY . /var/www/projeto_programador_database
WORKDIR /var/www/projeto_programador_database
EXPOSE 27017 28017